spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/master?characterEncoding=utf8&serverTimezone=GMT%2B8
          password: root
          username: root
        slave:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/slave?characterEncoding=utf8&serverTimezone=GMT%2B8
          password: root
          username: root